### ISSUE TITLE
assembly:InternalsVisibleToAttribute

### ISSUE THREAD

**Issue by balazs4** [balazs4/window-switcher#1]
https://github.com/balazs4/window-switcher/blob/c6ee25588927b26b889da6606033dcb214263131/window-switcher/Finders/WindowFinderMSUIA.cs#L44

you mean this here?
https://msdn.microsoft.com/en-us/library/system.runtime.compilerservices.internalsvisibletoattribute(v=vs.110).aspx#Anchor_6

**Comment by L0rdKlappstuhl** [comment]
Yep was to lazy and i was Not Sure of WE should sign Out assembly and what the keytoken would be
